export const translate_from = [
    { label: "Auto Detect", value: "auto" },
    { label: "English", value: "en" },
    { label: "Khmer", value: "km" },
    { label: "Spanish", value: "es" },
    { label: "French", value: "fr" },
    { label: "German", value: "de" },
    { label: "Chinese (Simplified)", value: "zh-CN" },
    { label: "Chinese (Traditional)", value: "zh-TW" },
    { label: "Japanese", value: "ja" },
    { label: "Korean", value: "ko" },
    { label: "Vietnamese", value: "vi" },
    { label: "Thai", value: "th" },
    { label: "Russian", value: "ru" },
    { label: "Arabic", value: "ar" },
    { label: "Indonesian", value: "id" },
    { label: "Italian", value: "it" },
    { label: "Portuguese", value: "pt" },
    { label: "Turkish", value: "tr" },
    { label: "Hindi", value: "hi" },
];

export const translate_to = [
    { label: "English", value: "en" },
    { label: "Khmer", value: "km" },
    { label: "Spanish", value: "es" },
    { label: "French", value: "fr" },
    { label: "German", value: "de" },
    { label: "Chinese (Simplified)", value: "zh-CN" },
    { label: "Chinese (Traditional)", value: "zh-TW" },
    { label: "Japanese", value: "ja" },
    { label: "Korean", value: "ko" },
    { label: "Vietnamese", value: "vi" },
    { label: "Thai", value: "th" },
    { label: "Russian", value: "ru" },
    { label: "Arabic", value: "ar" },
    { label: "Indonesian", value: "id" },
    { label: "Italian", value: "it" },
    { label: "Portuguese", value: "pt" },
    { label: "Turkish", value: "tr" },
    { label: "Hindi", value: "hi" },
];
