name: hyperionbox
base: core22
version: '2.2.5'
summary: An open-source anime and movie streaming app. # 79 char long summary
description: |
  An open-source anime and movie streaming app that support watch progress and download for many sources.

grade: stable
confinement: strict

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

apps:
  hyperionbox:
    command: usr/bin/HyperionBox
    desktop: usr/share/applications/HyperionBox.desktop
    extensions: [gnome]
    plugs:
      - network
      - network-status
      - network-bind
      - audio-playback
      
    # Add whatever plugs you need here, see https://snapcraft.io/docs/snapcraft-interfaces for more info.
    # The gnome extension already includes [ desktop, desktop-legacy, gsettings, opengl, wayland, x11, mount-observe, calendar-service ]
      - single-instance-plug # add this if you're using the single-instance plugin
    slots:
    # Add the slots you need to expose to other snaps
      - single-instance # add this if you're using the single-instance plugin
    environment:
      TMPDIR: $SNAP_USER_COMMON/tmp
      # WEBKIT_DISABLE_COMPOSITING_MODE: 1
# Add these lines only if you're using the single-instance plugin
# Check https://v2.tauri.app/plugin/single-instance/ for details
slots:
 single-instance:
   interface: dbus
   bus: session
   name: org.io_github_goodday360_hyperionbox.SingleInstance # Remember to change net_mydomain_MyApp to your app ID with "_" instead of "." and "-"

plugs:
  audio-playback:
    interface: audio-playback
  single-instance-plug:
    interface: dbus
    bus: session
    name: org.io_github_goodday360_hyperionbox.SingleInstance # Remember to change net_mydomain_MyApp to your app ID with "_" instead of "." and "-"

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  build-app:
    plugin: dump
    
    build-environment:
      - TAURI_SIGNING_PRIVATE_KEY: TAURI_SIGNING_PRIVATE_KEY
      - TAURI_SIGNING_PRIVATE_KEY_PASSWORD: TAURI_SIGNING_PRIVATE_KEY_PASSWORD


    build-snaps:
      - rustup/latest/stable
      - bun-js/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - gstreamer1.0-vaapi
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1

    source: .
    override-build: |
      set -eu
      rustup default stable

      bun install
      rm -f src-tauri/target/release/bundle/deb/*.deb
      bun tauri build --bundles deb 
      dpkg -x src-tauri/target/release/bundle/deb/*.deb $SNAPCRAFT_PART_INSTALL/
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta
      cp $SNAPCRAFT_PROJECT_DIR/snap_config/snapshots.yaml $SNAPCRAFT_PART_INSTALL/meta/
      sed -i -e "s|Icon=HyperionBox|Icon=/usr/share/icons/hicolor/256x256@2/apps/HyperionBox.png|g" $SNAPCRAFT_PART_INSTALL/usr/share/applications/HyperionBox.desktop