name: Build Snap (amd64 & arm64)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-snap:
    name: Build Snap
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]

    steps:
      - uses: actions/checkout@v3

      - name: Build Snap with Snapcraft
        id: snapcraft
        uses: snapcore/action-build@v1

      - name: Find built snap file
        id: find_snap
        run: |
          echo "snap_file_amd64=$(ls *_amd64.snap | head -n 1)" >> $GITHUB_OUTPUT
          echo "snap_file_arm64=$(ls *_arm64.snap | head -n 1)" >> $GITHUB_OUTPUT

      - name: Upload Snap artifact (amd64)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.find_snap.outputs.snap_file_amd64 }}
          path: ${{ steps.find_snap.outputs.snap_file_amd64 }}

      - name: Upload Snap artifact (arm64)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.find_snap.outputs.snap_file_arm64 }}
          path: ${{ steps.find_snap.outputs.snap_file_arm64 }}
