name: Build Snap (amd64 & arm64)

on:
  workflow_dispatch:
  push:
    branches: [main, window]

jobs:
  build-snap:
    name: Build Snap for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v3

      - name: Build Snap with Snapcraft
        id: snapcraft
        uses: snapcore/action-build@v1

      - name: Upload Snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.snapcraft.outputs.snap }}
          path: ${{ steps.snapcraft.outputs.snap }}
